name: Build Flutter Android & Notify Slack

on:
  pull_request:
    branches:
      - main
      - devlop  # Specify the branches to trigger on
    types:
      - opened  # Runs when a PR is opened
      - synchronize  # Runs when a PR is updated
      - reopened  # Runs when a PR is reopened
      - closed  # Runs when a PR is merged or closed

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          cache: true

      - name: Create .env File
        run: echo "${{ secrets.ENV_VARS }}" > .env
        shell: bash

      - name: Verify .env File (Debugging Step)
        run: cat .env

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  comment-on-pr:
    if: github.event.pull_request.merged == true  # Run only when merged
    name: Comment on PR with Artifact Links
    runs-on: ubuntu-latest
    needs: build-android

    steps:
      - name: Comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          COMMENT="🎉 *PR Merged!* 🚀  
          *Download Artifacts:*  
          - [Download APK](https://github.com/$REPO/actions/runs/${{ github.run_id }})
          "

          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments \
          -d "{\"body\": \"$COMMENT\"}"

  notify-slack:
    if: github.event.pull_request.merged == true  # Run only when merged
    name: Send Slack Notification
    runs-on: ubuntu-latest
    needs: build-android

    steps:
      - name: Send Notification to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "🚀 *PR Merged!* `${{ github.event.pull_request.title }}` by `${{ github.event.pull_request.user.login }}` into `develop` 🎉"
          SLACK_COLOR: "#36a64f"
